Rename 'scm_pipe2' to 'scm_fibers_pipe2'.
This fixes a build error with Guile 3.0.9:

  extensions/epoll.c:224:1: error: static declaration of 'scm_pipe2' follows non-static declaration

* extensions/epoll.c (scm_pipe2): Rename to...
(scm_fibers_pipe2): ... this.
(init_fibers_epoll): Adjust accordingly.